# Generated by Django 5.1.7 on 2025-03-20 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0005_usuarioextendido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLOUD',
            fields=[
                ('id_cloud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cloud', models.CharField(max_length=100)),
                ('siglas_cloud', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ambientes', models.ManyToManyField(related_name='clouds', to='it_infra_system.ambiente')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CLOUD',
                'ordering': ['nombre_cloud'],
            },
        ),
    ]
