# Generated by Django 5.1.7 on 2025-03-20 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0006_cloud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GERENCIA',
            fields=[
                ('id_gerencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gerencia', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITANTE',
            fields=[
                ('id_solicitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('puesto_solicitante', models.CharField(max_length=100)),
                ('email_solicitante', models.EmailField(max_length=254)),
                ('tel_solicitante', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
