# Generated by Django 5.1.7 on 2025-03-21 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0013_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_PROYECTO',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_status', models.CharField(max_length=100)),
                ('descripcion_status', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Proyecto',
                'verbose_name_plural': 'Estados de Proyecto',
                'db_table': 'status_proyecto',
                'ordering': ['nombre_status'],
            },
        ),
    ]
