# Generated by Django 5.1.7 on 2025-03-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0015_proyecto_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_compromiso_entrega',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_deploy',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_real_entrega',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_solicitud_blackhole',
        ),
    ]
