# Generated by Django 5.1.7 on 2025-03-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0017_proyecto_arquitecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioextendido',
            name='perfil',
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='perfiles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='it_infra_system.perfil'),
        ),
    ]
