# Generated by Django 5.1.7 on 2025-03-25 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0019_pais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RED',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_red', models.CharField(max_length=100)),
                ('descripcion_red', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
                'ordering': ['nombre_red'],
            },
        ),
    ]
