# Generated by Django 5.1.7 on 2025-04-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0025_vlan_red'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='red',
            options={'verbose_name': 'Red', 'verbose_name_plural': 'Redes'},
        ),
        migrations.RemoveField(
            model_name='red',
            name='descripcion_red',
        ),
        migrations.AddField(
            model_name='red',
            name='barra_red',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.AddField(
            model_name='red',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='red',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='red',
            name='segmento_red',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='red',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redes_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='red',
            name='uso_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_infra_system.uso_red'),
        ),
        migrations.AlterField(
            model_name='red',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='red',
            table='RED',
        ),
    ]
