# Generated by Django 5.1.7 on 2025-04-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0026_alter_red_options_remove_red_descripcion_red_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='descripcion_red',
            field=models.TextField(blank=True, null=True),
        ),
    ]
