# Generated by Django 5.1.7 on 2025-04-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0027_red_descripcion_red'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTROL_VLAN',
            fields=[
                ('id_control_vlan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tabla_vlan', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_vlans', to='it_infra_system.proyecto')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uso_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_vlans', to='it_infra_system.uso_red')),
            ],
            options={
                'verbose_name': 'Control de VLAN',
                'verbose_name_plural': 'Controles de VLAN',
                'db_table': 'CONTROL_VLAN',
                'ordering': ['nombre_tabla_vlan'],
            },
        ),
    ]
