# Generated by Django 5.1.7 on 2025-04-11 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0034_cpu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VTI',
            fields=[
                ('vti_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vti', models.CharField(max_length=100)),
                ('siglas', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VTI',
                'verbose_name_plural': 'VTIs',
                'ordering': ['vti_id'],
            },
        ),
    ]
