# Generated by Django 5.1.7 on 2025-04-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0035_vti'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS it_infra_system_ram; DROP TABLE IF EXISTS it_infra_system_vram;',
            reverse_sql='',
        ),
    ]
