# Generated by Django 5.1.7 on 2025-03-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0009_solicitante_gerencia_solicitante_puesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='id_solicitante',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
