# Generated by Django 5.1.7 on 2025-03-21 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0012_vlan_ambiente_alter_vlan_cloud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PROYECTO',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_deploy', models.DateField(blank=True, null=True)),
                ('fecha_compromiso_entrega', models.DateField()),
                ('fecha_solicitud_blackhole', models.DateField(blank=True, null=True)),
                ('fecha_real_entrega', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
            },
        ),
    ]
