# Generated by Django 5.1.7 on 2025-04-01 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0022_vlan_uso_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='uso_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_infra_system.uso_red', verbose_name='Uso de Red'),
        ),
    ]
