# Generated by Django 5.1.7 on 2025-04-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0024_vlan_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='it_infra_system.red'),
        ),
    ]
