# Generated by Django 5.1.7 on 2025-04-03 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0028_control_vlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLAN_IP',
            fields=[
                ('id_vlan_ip', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='disponible', max_length=20)),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='it_infra_system.vlan')),
            ],
            options={
                'verbose_name': 'IP de VLAN',
                'verbose_name_plural': 'IPs de VLAN',
                'db_table': 'vlan_ip',
            },
        ),
    ]
