# Generated by Django 5.1.7 on 2025-04-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0030_control_vlan_rango_ips_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='ip_fin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='red',
            name='ip_inicio',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
