# Generated by Django 5.1.7 on 2025-04-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0031_red_ip_fin_red_ip_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_vlan',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_vlans', to='it_infra_system.proyecto'),
        ),
    ]
