# Generated by Django 5.1.7 on 2025-04-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0032_alter_control_vlan_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='numero_vlan',
            field=models.IntegerField(help_text='Número de VLAN (1-4094)'),
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('numero_vlan', 'cloud')},
        ),
    ]
