# Generated by Django 5.1.7 on 2025-04-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0033_alter_vlan_numero_vlan_alter_vlan_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('cpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('core_cpu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
                'db_table': 'CPU',
            },
        ),
    ]
