# Generated by Django 5.1.7 on 2025-04-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0036_remove_ram_vram'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('ram_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('vti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rams', to='it_infra_system.vti')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAMs',
                'ordering': ['ram_id'],
            },
        ),
    ]
