# Generated by Django 5.1.7 on 2025-04-14 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_infra_system', '0037_ram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_EQUIPO',
            fields=[
                ('statuse_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_statuse', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_statuse', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipo',
                'db_table': 'status_equipo',
                'ordering': ['nombre_statuse'],
            },
        ),
    ]
